/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.ImageIcon;
import classes.Image;
import java.io.File;
import java.util.ArrayList;

/**
 *
 * @author Jhonny Diaz
 */
public final class MainWindow extends javax.swing.JFrame {
    Image imageController = new Image();
    ShowMaps _showMaps;
    
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        //Load the all the maps in the carpet
        File folder = new File("src\\main\\java\\images");
        ArrayList<String> mapsList = getFolderElements(folder);
        addItems(mapsList);
        
        
        lblWallpaper.setIcon(new ImageIcon("src\\main\\java\\wallpapersAndOutputs\\wallpaper.jpg"));
        
        
  
    }
    
    public void addItems(ArrayList<String> elements){
        for(String i : elements){
                this.jComboBoxMaps.addItem(i);
            }
    
    }
    
    public void printElements(File folder){
        
        for (File file : folder.listFiles()) {
            if (!file.isDirectory()) {
                    System.out.println(file.getName());
            } 
            else {
                printElements(file);
            }
	}
    
    }
    
    public ArrayList<String> getFolderElements(File folder){
        
        ArrayList<String> elementsList = new ArrayList<>();
        
        for (File file : folder.listFiles()) {
            if (!file.isDirectory()) {
                elementsList.add(file.getName());
                //System.out.println(file.getName());
            } 
            else {
                getFolderElements(file);
            }
	}
        
        return elementsList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAccept = new javax.swing.JButton();
        jComboBoxMaps = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        lblIndication = new javax.swing.JLabel();
        lblWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAccept.setText("ACEPTAR");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        getContentPane().add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        jComboBoxMaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMapsActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxMaps, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        lblTitle.setFont(new java.awt.Font("Arcade", 0, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Laberintos ->Algoritmos Geneticos");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        lblIndication.setFont(new java.awt.Font("Arcade", 0, 36)); // NOI18N
        lblIndication.setForeground(new java.awt.Color(255, 255, 255));
        lblIndication.setText("Por favor seleccione el mapa:");
        getContentPane().add(lblIndication, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 500, 50));
        getContentPane().add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 436));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMapsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxMapsActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        imageController.getImageInfo("src\\main\\java\\images\\" + jComboBoxMaps.getSelectedItem().toString());
        _showMaps = new ShowMaps(imageController.matrix);
        this.setVisible(false);
        _showMaps.setVisible(true);
        
        
    }//GEN-LAST:event_btnAcceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JComboBox<String> jComboBoxMaps;
    private javax.swing.JLabel lblIndication;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWallpaper;
    // End of variables declaration//GEN-END:variables
}
