/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author Jhonny Diaz
 */
public class ShowMaps extends javax.swing.JFrame {
    
    private javax.swing.JButton[][] btnPixels;
    
    /**
     * Creates new form ShowMaps
     */
    public ShowMaps() {
        createButtons(0,0);
        initComponents();
    }
    public ShowMaps(int matrix[][]) {
        createButtons(matrix.length,matrix[0].length);
        printMap(matrix);
        
        initComponents();
        this.getContentPane().setBackground(new Color(64,64,150));
        btnStop.setBackground(Color.red);
        
        
    }
    
    
    private void createButtons(int x, int y) {
        btnPixels = new javax.swing.JButton[x][y];
        
        int space = 5;
        

        int rowHor = 650;
        int colVer = 35;

        int vertical = 45;
        int horizontal;

        for (int i = 0; i < btnPixels.length; i++) {
            horizontal = 50;
            for (int j = 0; j < btnPixels[i].length; j++) {
                btnPixels[i][j] = new javax.swing.JButton();
                btnPixels[i][j].setBounds(horizontal, vertical, 7, 7);
                btnPixels[i][j].setBackground(new java.awt.Color(30, 30, 30));
                //btnPixels[i][j].
                add(btnPixels[i][j]);
                horizontal += space;
            }
            vertical += space;
            colVer += space;
            rowHor += space;
        }         
    }
    
    
    public void printMap(int matrix[][]){
        
        
        for (int i = 0; i < btnPixels.length; i++) {
            
            for (int j = 0; j < btnPixels[i].length; j++) {
                if (matrix[i][j] == 0) {
                    btnPixels[i][j].setBackground(Color.BLACK);
                }
                if (matrix[i][j] == 1) {
                    btnPixels[i][j].setBackground(Color.white);
                }
                if (matrix[i][j] == 2) {
                    btnPixels[i][j].setBackground(Color.red);
                }
                
                
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAcceptInfo = new javax.swing.JButton();
        spnIndividualsNumber = new javax.swing.JSpinner();
        spnMinimumChange = new javax.swing.JSpinner();
        lblMinimunChange = new javax.swing.JLabel();
        btnStop = new javax.swing.JButton();
        lblIndividualNumbers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAcceptInfo.setText("ACCEPT");

        lblMinimunChange.setText("Cambio mínimo");

        btnStop.setText("STOP");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lblIndividualNumbers.setText("Cantidad de Individuos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblIndividualNumbers)
                .addGap(18, 18, 18)
                .addComponent(spnIndividualsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(lblMinimunChange)
                .addGap(18, 18, 18)
                .addComponent(spnMinimumChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(btnAcceptInfo)
                .addGap(400, 400, 400)
                .addComponent(btnStop))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblIndividualNumbers))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(spnIndividualsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblMinimunChange))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(spnMinimumChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnAcceptInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnStop)))
                .addContainerGap(497, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowMaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowMaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowMaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowMaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowMaps().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptInfo;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lblIndividualNumbers;
    private javax.swing.JLabel lblMinimunChange;
    private javax.swing.JSpinner spnIndividualsNumber;
    private javax.swing.JSpinner spnMinimumChange;
    // End of variables declaration//GEN-END:variables
}
