/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import classes.Environment;
import classes.Individual;

/**
 *
 * @author Jhonny Diaz
 */
public class ShowMaps extends javax.swing.JFrame {
    
    private javax.swing.JButton[][] btnPixels;
    private int[][] matrix;
    private Environment env;
    private int generationsToCheck;
    private float percentage_similarity;
    private boolean areDifferent;  // Used for the stop condtion
    
    /**
     * Creates new form ShowMaps
     */
    public ShowMaps() {
        createButtons(0,0);
        initComponents();
    }
    public ShowMaps(int matrix[][]) {
        areDifferent = true; 
        
        createButtons(matrix.length, matrix[0].length);
        printMap(matrix);
        
        initComponents();
        this.getContentPane().setBackground(new Color(64,64,150));
        btnStop.setBackground(Color.red);
        cmbGeneration.setEnabled(false);
        cmbIndividual.setEnabled(false);
        this.matrix = matrix;
        spnMinimumChange.setValue(98);
        spnRadio.setValue(5);
        spnIndividualsNumber.setValue(120);
        spnGnerationsAmount.setValue(50);
        jButtonContinue.setEnabled(false);
        btnGeonolgy.setEnabled(false);
        btnRecreate.setEnabled(false);
        setResizable(false);
    }
    
    public void clean_matrix(Individual[] individuals, int matrix[][]){
        int i, j;
        for(Individual individual : individuals){
            i = individual.x;
            j = individual.y;
            
            if (matrix[i][j] == 0) {
                    btnPixels[i][j].setBackground(Color.BLACK);
                }
            if (matrix[i][j] == 1) {
                btnPixels[i][j].setBackground(Color.white);
            }
            if (matrix[i][j] == 2) {
                btnPixels[i][j].setBackground(Color.red);
            }   
        }
    }
    
    
    public void draw_individuals(Individual[] individuals){
        for(Individual individual : individuals){
            btnPixels[individual.x][individual.y].setBackground(new java.awt.Color(0, 255, 0));
        }
    }
    
    
    private void createButtons(int x, int y) {
        btnPixels = new javax.swing.JButton[x][y];
        
        int space = 5;
        

        int vertical = 45;
        int horizontal;

        for (int i = 0; i < btnPixels.length; i++) {
            horizontal = 50;
            for (int j = 0; j < btnPixels[i].length; j++) {
                btnPixels[i][j] = new javax.swing.JButton();
                btnPixels[i][j].setBounds(horizontal, vertical, 7, 7);
                btnPixels[i][j].setBackground(new java.awt.Color(30, 30, 30));
                //btnPixels[i][j].
                add(btnPixels[i][j]);
                horizontal += space;
            }
            vertical += space;

        }         
    }
    
    
    public void printMap(int matrix[][]){
        
        
        for (int i = 0; i < btnPixels.length; i++) {
            
            for (int j = 0; j < btnPixels[i].length; j++) {
                if (matrix[i][j] == 0) {
                    btnPixels[i][j].setBackground(Color.BLACK);
                }
                if (matrix[i][j] == 1) {
                    btnPixels[i][j].setBackground(Color.white);
                }
                if (matrix[i][j] == 2) {
                    btnPixels[i][j].setBackground(Color.red);
                }
                
                
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAcceptInfo = new javax.swing.JButton();
        spnIndividualsNumber = new javax.swing.JSpinner();
        spnMinimumChange = new javax.swing.JSpinner();
        lblMinimunChange = new javax.swing.JLabel();
        btnStop = new javax.swing.JButton();
        lblIndividualNumbers = new javax.swing.JLabel();
        jButtonContinue = new javax.swing.JButton();
        labelGenerations = new javax.swing.JLabel();
        spnGnerationsAmount = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        spnRadio = new javax.swing.JSpinner();
        spnMutation = new javax.swing.JSpinner();
        lblMutation = new javax.swing.JLabel();
        btnGeonolgy = new javax.swing.JButton();
        lblGenerationCheck = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRecreate = new javax.swing.JButton();
        cmbGeneration = new javax.swing.JComboBox<>();
        cmbIndividual = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAcceptInfo.setText("ACCEPT");
        btnAcceptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptInfoActionPerformed(evt);
            }
        });

        spnMinimumChange.setModel(new javax.swing.SpinnerNumberModel(0, null, 99, 1));
        spnMinimumChange.setAutoscrolls(true);

        lblMinimunChange.setText("Similitud");

        btnStop.setText("STOP");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lblIndividualNumbers.setText("Cantidad de Individuos");

        jButtonContinue.setText("Continue");
        jButtonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueActionPerformed(evt);
            }
        });

        labelGenerations.setText("Cantidad de generaciones");

        jLabel1.setText("Radio");

        spnRadio.setModel(new javax.swing.SpinnerNumberModel(0, null, 10, 1));

        spnMutation.setModel(new javax.swing.SpinnerNumberModel(5, null, 99, 1));

        lblMutation.setText("Mutacion");

        btnGeonolgy.setText("Ver Geonologia");
        btnGeonolgy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeonolgyActionPerformed(evt);
            }
        });

        lblGenerationCheck.setText("Generacion");

        jLabel2.setText("Individuo");

        btnRecreate.setText("Recrear");
        btnRecreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIndividualNumbers)
                        .addGap(18, 18, 18)
                        .addComponent(spnIndividualsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblMinimunChange)
                        .addGap(18, 18, 18)
                        .addComponent(spnMinimumChange, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelGenerations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnGnerationsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(lblMutation, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnMutation, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStop))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGenerationCheck, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbGeneration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(344, 344, 344)
                                .addComponent(btnAcceptInfo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGeonolgy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonContinue))
                                    .addComponent(btnRecreate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblIndividualNumbers))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblMinimunChange))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnMinimumChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelGenerations)
                            .addComponent(spnGnerationsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(spnRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMutation)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStop)
                            .addComponent(spnMutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spnIndividualsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonContinue)
                        .addGap(18, 18, 18)
                        .addComponent(btnAcceptInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGenerationCheck)
                            .addComponent(cmbGeneration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGeonolgy))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRecreate))))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnStopActionPerformed

    private void jButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinueActionPerformed
        
        int i = env.generationsList.size()-1;  // Index of the last generation
        
        if (i < generationsToCheck || areDifferent){
            clean_matrix(env.generationsList.get(i).individuals, matrix);  // Its the turn of a new generation, we must clean
            
            float last_generation_score, penultimate_generation_score;  // Used for the comparisons    


            penultimate_generation_score = env.generationsList.get(i).generation_average;
            
            env.createNewGeneration();  // we create a new generation to continue improving the individuals
            i++;  // Update the index
            cmbGeneration.addItem(String.valueOf(i));
            
            last_generation_score = env.generationsList.get(i).generation_average;
            draw_individuals(env.generationsList.get(i).individuals);



             /*The last generation was better than the penultimate
            we check how good was that improvement*/
            areDifferent = env.areDifferent(percentage_similarity, penultimate_generation_score, last_generation_score);
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonContinueActionPerformed

    private void btnAcceptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptInfoActionPerformed
        // TODO add your handling code here:
        percentage_similarity = (int) spnMinimumChange.getValue();
        percentage_similarity /= 100;
        generationsToCheck = (int) spnGnerationsAmount.getValue();
        
        int amountIndividuals = (int) spnIndividualsNumber.getValue();
        int mutationIndex = (int) spnMutation.getValue();
        int radio = (int) spnRadio.getValue();
        
        env = new Environment(amountIndividuals, matrix, radio, mutationIndex);
        
        spnMinimumChange.setEnabled(false);
        spnIndividualsNumber.setEnabled(false);
        spnGnerationsAmount.setEnabled(false);
        spnMutation.setEnabled(false);
        spnRadio.setEnabled(false);
        
        btnAcceptInfo.setEnabled(false);
        jButtonContinue.setEnabled(true);
        
        cmbGeneration.setEnabled(true);
        cmbIndividual.setEnabled(true);
        
        btnGeonolgy.setEnabled(true);
        btnRecreate.setEnabled(true);
        
        cmbGeneration.addItem("0");
        for(int i = 0; i < amountIndividuals; i++){
            cmbIndividual.addItem(String.valueOf(i));
        }
        
        env.makeFirstGeneration(); // Starts creating the first generation of random individuals
        draw_individuals(env.generationsList.get(0).individuals);
    }//GEN-LAST:event_btnAcceptInfoActionPerformed

    private void btnGeonolgyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeonolgyActionPerformed
        // TODO add your handling code here:
        env.generationsList.get(cmbGeneration.getSelectedIndex()).individuals[cmbGeneration.getSelectedIndex()].getGeonolgy();
    }//GEN-LAST:event_btnGeonolgyActionPerformed

    private void btnRecreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecreateActionPerformed
        RecreateGui recreate = new RecreateGui(matrix, env.generationsList.get(cmbGeneration.getSelectedIndex()).individuals);
        recreate.setVisible(true);
    }//GEN-LAST:event_btnRecreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowMaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowMaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowMaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowMaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowMaps().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptInfo;
    private javax.swing.JButton btnGeonolgy;
    private javax.swing.JButton btnRecreate;
    private javax.swing.JButton btnStop;
    private javax.swing.JComboBox<String> cmbGeneration;
    private javax.swing.JComboBox<String> cmbIndividual;
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelGenerations;
    private javax.swing.JLabel lblGenerationCheck;
    private javax.swing.JLabel lblIndividualNumbers;
    private javax.swing.JLabel lblMinimunChange;
    private javax.swing.JLabel lblMutation;
    private javax.swing.JSpinner spnGnerationsAmount;
    private javax.swing.JSpinner spnIndividualsNumber;
    private javax.swing.JSpinner spnMinimumChange;
    private javax.swing.JSpinner spnMutation;
    private javax.swing.JSpinner spnRadio;
    // End of variables declaration//GEN-END:variables
}
